{% set name = "locate" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/locate-{{ version }}.tar.gz
  sha256: 432750f5b7e89f8c99942ca7d8722ccd1e7954b20e6a973027fccb6cc00af857

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.4
    - setuptools-scm
    - pip
  run:
    - python >=3.4

test:
  source_files:
    - tests
  imports:
    - locate
  commands:
    - pip check
    - pytest -vvv --capture=tee-sys tests
  requires:
    - pip
    - pytest

about:
  home: https://github.com/AutoActuary/locate
  summary: Locate the file location of your current running script.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
